name: viserpay_merchant
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  awesome_dialog: ^3.0.2
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dotted_border: ^2.0.0+2
  file_picker: ^6.1.1
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^14.7.8
  flutter:
    sdk: flutter
  flutter_exit_app: ^1.1.2
  flutter_local_notifications: ^16.2.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  flutter_widget_from_html: ^0.14.9
  get: ^4.6.5
  http: ^1.1.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  intl: ^0.19.0
  lottie: ^2.3.1
  octo_image: ^2.0.0
  path_provider: ^2.0.9
  permission_handler: ^11.1.0
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  share_plus: ^7.2.1
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/logo/
    - assets/animation/
